### ISSUE TITLE
Fix style failures

### ISSUE THREAD

**Issue by Jeroen-G** [stephenlake/laravel-sanity#8]
Hi there!

This package is just what I was looking for (no need to reinvent this wheel!)🥇
I wondered if it is/can be possible to fix the CS errors that might pop up after the style runner. I could of course try out to help you here in case it needs some work!

**Comment by stephenlake** [comment]
Hi @Jeroen-G 

I actually deliberately left out an autofixer mainly for the reason that one doesn't learn or form a habit of writing better code if it's fixed for them every time there's an issue.

However, behind the scenes PHP-CS actually makes it really simple to autofix the issues that it can fix. Two commands will apply a diff and fix whatever it can:

```
php ./vendor/bin/phpcs --report-diff=storage/changes.diff

patch -p0 -ui storage/changes.diff
```

And I actually did write a command for this, but didn't apply it to the package:

```php
<?php

namespace App\Commands;

use Illuminate\Console\Command;
use Symfony\Component\Process\Process;

class TestStyle extends Command
{
    /**
     * The name and signature of the console command.
     *
     * @var string
     */
    protected $signature = 'test:style {--autofix}';

    /**
     * The console command description.
     *
     * @var string
     */
    protected $description = 'Run style tests';

    /**
     * Execute the console command.
     *
     * @return void
     */
    public function handle()
    {
        $process = new Process('php ./vendor/bin/phpcs --report-diff=storage/changes.diff');
        $process->setTimeout(null);
        $process->setTty(true);
        $process->run(function ($type, $buffer) {
            echo $buffer;
        });

        if ($this->option('autofix')) {
            $autofix = new Process('patch -p0 -ui storage/changes.diff');
            $autofix->setTimeout(null);
            $autofix->setTty(true);
            $autofix->run(function ($type, $buffer) {
                echo $buffer;
            });
        }
    }
}
```

**Comment by Jeroen-G** [comment]
Great, thanks a lot! There's always that misplaced space that could be removed. :)

Maybe you could start a organisation on GitHub for additional runners, an install command similar to that of laravel zero could fetch those on demand.

**Comment by stephenlake** [comment]
I think it'd be easier to just submit PR's and make them optional. I'm a little tight on time for the next few weeks while I attend to projects that pay the bills :octopus: but you're more than welcome to submit a PR.
